version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./examples/.env  # Path to the .env file in the config directory
    command: python startMuseStream.py && python stream-muse-test.py
